client_config_backend: settings
client_config:
  client_id: 453671677558-j367pndqnictkohoevrn4ee8tt8gqngk.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install