# Configure error setup and specify algorithms to run

[general]
# Visualization will be generated iff. iterations are set to 1
iterations = 1
random_receiver = false
num_senders = 20
    
    [general.receiver_position]
    x = 0
    y = 0
    z = 0

[error]
von_mises_concentration = 132.312 # expected 5 deg angular std. deviation
delta_error = 0.1 # 10cm standard deviation
wall_error = 0.05 # 5% of reflection will wrongly be assigned

[algorithms]

    [algorithms.clustering]
    inversion = true
    projection = true
    stereographic_projection = true

    [algorithms.wall_normal]
    all_pairs = true
    linear_all_pairs = false
    disjoint_pairs = true
    overlapping_pairs = true

    [algorithms.wall_selection]
    largest_cluster = true
    narrowest_cluster = true
    unweighted_average = true
    weighted_average_wall_distance = false

    [algorithms.localization]
    wall_direction = true
    map_to_wall_normal = true
    reflection_geometry = true
    closest_lines = true
    closest_lines_extended = true
