client_config_backend: settings
client_config:
  client_id: 271893597243-dn4b0ln9o9f5jfjnd7i1s1n9j1cr4dhj.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install